<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Operadores</title>
</head>
<body>
    <?php
    $a = 5;
    $b = 8;

    echo'El resultado de sumar $a y $b es: ' . $a + $b;
    echo'El resultado de restar $a y $b es: ' . $a - $b;
    echo'El resultado de multiplicar $a y $b es: ' . $a * $b;
    echo'El resultado de dividir $a y $b es: ' . $a / $b;

    ?>
</body>
</html>